apiVersion: v1
kind: Namespace
metadata:
  name: team3-nginx # 새로운 네임스페이스 생성
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team3-nginx
  name: deploy-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        name: nginx

      topologySpreadConstraints:
        - maxSkew: 1  # 각 가용영역(또는 노드)에 최대 1개 차이까지만 허용
          topologyKey: topology.kubernetes.io/zone  # 가용영역 단위로 분산
          whenUnsatisfiable: ScheduleAnyway  # 조건을 만족하지 않아도 스케줄링은 시도
          labelSelector:
            matchLabels:
              app: deploy-nginx

      containers:
      - name: team3-nginx
        image: 635697986322.dkr.ecr.ap-northeast-2.amazonaws.com/team3-ecr:nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: team3-nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team3-ingress
  namespace: team3-nginx
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:635697986322:certificate/a1e705ad-a4a4-4cc6-9e3d-c6b31ff6bba0
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: team3-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-nginx
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
